version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install poetry
      - pip install torch==1.13.1+cpu --extra-index-url https://download.pytorch.org/whl/cpu
      - poetry config virtualenvs.create false
    post_install:
      - poetry install -E docs

sphinx:
  configuration: docs/conf.py
  
submodules:
  include:
     - "docs/tutorials/"
  recursive: true