[tool.isort]
include_trailing_comma = true
multi_line_output = 3
profile = "black"
skip_glob = ["docs/*", "cpa/__init__.py"]

[tool.poetry]
authors = ["Mohsen Naghipourfar <naghipourfar@berkeley.edu>", "Mohammad Lotfollahi <mohammad.lotfollahi@helmholtz-muenchen.de>"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
description = "Compositional Perturbation Autoencoder (CPA)"
documentation = "https://cpa-tools.readthedocs.io"
homepage = "https://github.com/theislab/cpa/"
license = "BSD-3-Clause"
name = "cpa-tools"
packages = [
    { include = "cpa" },
]
readme = "README.md"
version = "0.7.2"

[tool.poetry.dependencies]
adjustText = { version = "*", optional = true }
anndata = ">=0.7.5"
toml = ">=0.10"
importlib-metadata = { version = "^1.0", python = "<=3.10" }
pytest = { version = ">=4.4", optional = true }
python = "^3.10"
scvi-tools = ">=0.16.4"
scanpy = "^1.9.5"
scipy = {version = "*"}
rdkit-pypi = "^2022.9.5"

[tool.poetry.extras]
dev = ["black", "pytest", "flake8", "codecov", "scanpy", "loompy", "jupyter",
    "nbformat", "nbconvert", "pre-commit", "isort"]
docs = [
#    "jinja2<3.0.3",
    "scanpy",
    "sphinx",
    "scipy",
    "scanpydoc",
    "nbsphinx",
    "nbsphinx-link",
    "ipython",
    "toml",
    "pydata-sphinx-theme",
    "typing_extensions",
    "sphinx-autodoc-typehints",
    "sphinx_gallery",
    "sphinx-rtd-theme",
    "pydata-sphinx-theme",
]
tutorials = ["scanpy", "leidenalg", "python-igraph", "loompy", "scikit-misc", "scipy", "toml"]

[tool.poetry.dev-dependencies]

[build-system]
build-backend = "poetry.masonry.api"
requires = [
    "poetry>=1.0",
    "setuptools", # keep it here or "pip install -e" would fail
]
