[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "cpa-tools"
description = "Compositional Perturbation Autoencoder (CPA)"
version = "0.8.0"
readme = "README.md"
license = "MIT"
homepage = "https://cpa-tools.readthedocs.io/en/latest/"
repository = "https://github.com/theislab/cpa"
documentation = "https://cpa-tools.readthedocs.io/en/latest/"

authors = [
    "Mohsen Naghipourfar <naghipourfar@berkeley.edu>",
    "Mohammad Lotfollahi <mohammad.lotfollahi@helmholtz-muenchen.de>",
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Natural Language :: English",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
]

packages = [
    {include = "cpa"},
]

[tool.poetry.dependencies]
adjustText="*"
# "anndata>=0.7.5",
importlib-metadata="*"
scvi-tools = { version = ">=0.20" }
scanpy="*"
scipy="*"
rdkit-pypi="*"
# "llvmlite>=0.40.1",
# "chex==0.1.8",
# "numba>=0.57.1",
# "numpy>=1.24.4",

[tool.poetry.extras]
tests = [
    "pytest",
    "pytest-cov",
]  
editing = [
    "black",
    "flake8",
    "jupyter",
    "nbformat",
    "nbconvert",
    "pre-commit",
    "ruff",
]  # dependencies for editing and committing code
# dev = ["cpa-tools[editing,tests]"]  # dependencies for dev work

autotune = [
    "ray",
    "ipython",
    "tensorboard",
]  

scanpy = [
    "scanpy"
]

# docsbuild = ["cpa-tools[docs]"]  # docs build dependencies

docs = [
    "scanpy",
    "sphinx",
    "scipy",
    "scanpydoc",
    "nbsphinx",
    "nbsphinx-link",
    "ipython",
    "toml",
    "pydata-sphinx-theme",
    "typing_extensions",
    "sphinx-autodoc-typehints",
    "sphinx_gallery",
    "sphinx-rtd-theme",
]
tutorials = [
    "scanpy", 
    "leidenalg", 
    "python-igraph", 
    "loompy", 
    "scikit-misc", 
    "scipy", 
    "toml"
]

[tool.hatch.build.targets.wheel]
packages = ['cpa']

[tool.distutils.bdist_wheel]
universal = true

[tool.coverage.run]
source = ["cpa"]
omit = [
    "**/test_*.py",
]

