[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cpa-tools"
description = "Compositional Perturbation Autoencoder (CPA)"
version = "0.8.0"
requires-python = "^3.10.12"
readme = "README.md"
license = {file = "LICENSE"}
documentation = "https://cpa-tools.readthedocs.io"
homepage = "https://github.com/theislab/cpa/"

authors = [
    {name = "Mohsen Naghipourfar", email = "naghipourfar@berkeley.edu"},
    {name = "Mohammad Lotfollahi", email = "mohammad.lotfollahi@helmholtz-muenchen.de"},
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Natural Language :: English",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
]

dependencies = [
    "adjustText",
    "anndata>=0.7.5",
    "toml>=0.10",
    "importlib-metadata",
    "python>=3.9",
    "scvi-tools>=0.20.2",
    "scanpy>=1.9.5",
    "scipy",
    "rdkit-pypi>=2022.9.5",
    "llvmlite>=0.40.1",
    "chex==0.1.8",
    "numba>=0.57.1",
    "numpy>=1.24.4",
]

[project.optional-dependencies]
tests = [
    "pytest",
    "pytest-cov",
    "cpa-tools[optional]",
]  # dependencies for running the test suite
editing = [
    "black",
    "flake8",
    "jupyter",
    "nbformat",
    "nbconvert",
    "pre-commit",
    "ruff",
]  # dependencies for editing and committing code
dev = ["cpa-tools[editing,tests]"]  # dependencies for dev work

autotune = [
    "ray[tune]>=2.5.0",
    "ipython",
    "tensorboard",
]  

scanpy = [
    "scanpy"
]

docsbuild = ["cpa-tools[docs,optional]"]  # docs build dependencies
optional = [
    "cpa-tools[autotune,scanpy]"
] 

docs = [
#    "jinja2<3.0.3",
    "scanpy",
    "sphinx",
    "scipy",
    "scanpydoc",
    "nbsphinx",
    "nbsphinx-link",
    "ipython",
    "toml",
    "pydata-sphinx-theme",
    "typing_extensions",
    "sphinx-autodoc-typehints",
    "sphinx_gallery",
    "sphinx-rtd-theme",
]
tutorials = [
    "scanpy", 
    "leidenalg", 
    "python-igraph", 
    "loompy", 
    "scikit-misc", 
    "scipy", 
    "toml"
]

[tool.hatch.build.targets.wheel]
packages = ['cpa']

[tool.coverage.run]
source = ["cpa"]
omit = [
    "**/test_*.py",
]

